version: 1.2.0.{build}
configuration: Release
init:
- ps: $env:GIT_SHORT_HASH = $env:APPVEYOR_REPO_COMMIT.substring(0,7)
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}-$(GIT_SHORT_HASH)'
build:
  verbosity: minimal
after_build:
- ps: nuget pack "$env:APPVEYOR_BUILD_FOLDER\ExpressionEvaluator\ExpressionEvaluator.csproj" -Properties "Configuration=Release;Platform=AnyCPU" -Version $env:APPVEYOR_BUILD_VERSION
artifacts:
- path: '**\*.nupkg'
deploy:
- provider: NuGet
  api_key:
    secure: H0i5Ls4cXuCST2mf4/cblZpr4NuJ7sIB9PQACXsDjbCBknXYD4uZOXRJmfw70Rf5
  on:
    branch: master
